version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=test001


  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 10; done; python create_db.py && uvicorn main:app --reload --host 0.0.0.0 --port 8000'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/test001
    depends_on:
      - db

volumes:
  postgres_data: